## NumPy 

- NumPy stands for numerical python - Turns data into a series of numbers. Machines only understand numbers. It offers fast computation on arrays and lists.
- Fast due to a process called vectorization which aims to do calculations by avoiding loops.
- Vectorization is achieved by broadcasting(How numpy handles arrays with different shapes)

In [1]:
import numpy as np

## 1. Datatypes and attributes
- one dimension array - vector
- more than one array - matrix ie a2, a3

In [6]:
# Create a 1-dimensional NumPy array using np.array() - which is also called a vector 
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[2,3,4],[5,6,7]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],[[10,11,12],
                          [13,14,15],
                          [16,17,18]]])

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.size, type(a1)

((3,), 1, 3, numpy.ndarray)

In [9]:
# a2
a2.shape, a2.ndim, a2.size , type(a2)

((2, 3), 2, 6, numpy.ndarray)

In [10]:
#a3
a3.shape, a3.ndim, a3.size, type(a3)

((2, 3, 3), 3, 18, numpy.ndarray)

In [11]:
# You can create a Pandas DataFrame out of the arrays 
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  2  3  4
1  5  6  7

## 2. Creating arrays
- `np.array()`
- `np.ones()`
- `np.zeros()`
- `np.arange()`
- `np.random.randint(10, size=())`
- `np.random.seed()`- creates pseudo random numbers

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
#Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3) #start, end , step
range_array 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7,2))
random_array

array([[3, 7],
       [2, 2],
       [2, 2],
       [8, 3],
       [4, 7],
       [4, 2],
       [1, 5]])

In [21]:
 #Create a random array of floats between 0 & 1 of shape (3, 5)
float_array = np.random.random((3,5)) #also np.random.rand
float_array

array([[0.86622444, 0.76896008, 0.92040175, 0.35970037, 0.5958222 ],
       [0.54113857, 0.73605153, 0.86975828, 0.43421621, 0.39049023],
       [0.50391315, 0.68460968, 0.16825278, 0.40369221, 0.81053403]])

In [24]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

How to find unique values in an array

In [32]:
a4 = np.array([[2,4,3],[5,1,8]])
a4

array([[2, 4, 3],
       [5, 1, 8]])

In [33]:
np.unique(a4) # returns unique elements in an array sorted

array([1, 2, 3, 4, 5, 8])

## 3. Viewing arrays and matrices(indexing)

In [34]:
# Find the 0'th index of a4 array 
a4[0]

array([2, 4, 3])

In [37]:
# Get the first two rows 
a4[:2]

array([[2, 4, 3],
       [5, 1, 8]])

In [38]:
# Get the first 2 values of the first 2 rows 
a4[:2]

array([[2, 4, 3],
       [5, 1, 8]])

## 4. Manipulating arrays

Addition

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones  both of size (3, 5)
random_arr = np.random.randint(10, size=(3,5))
ones_arr = np.ones((3,5))


In [52]:
random_arr

array([[7, 1, 0, 6, 6],
       [7, 4, 2, 7, 5],
       [2, 0, 2, 4, 2]])

In [53]:
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
# Add the two arrays together
n1 = random_arr + ones_arr
n1

array([[8., 2., 1., 7., 7.],
       [8., 5., 3., 8., 6.],
       [3., 1., 3., 5., 3.]])

In [55]:
# Create another array of ones of shape (5, 3)
a5 = np.ones((5,3))
a5, a5.shape

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 (5, 3))

In [56]:
# Try add the array of ones and the other most recent array together
ones_arr + a5  # will throw a shape error

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [57]:
# How to fix the above error 
# by reshaping or using transpose 

In [58]:
# Create another array of ones of shape (3, 5)
a6 = np.ones((3,5))
a6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
# Subtract the new array of ones from the other most recent array
random_arr - a6

array([[ 6.,  0., -1.,  5.,  5.],
       [ 6.,  3.,  1.,  6.,  4.],
       [ 1., -1.,  1.,  3.,  1.]])

In [61]:
# Multiply the ones array with the latest array
random_arr  * a6

array([[7., 1., 0., 6., 6.],
       [7., 4., 2., 7., 5.],
       [2., 0., 2., 4., 2.]])

In [62]:
# create an array and find the mean 
array1 = np.array([[2,3,4],[4,6,8]])
np.mean(array1)

4.5

In [68]:
# find the max of array1
np.max(array1)
# find the index of the maximum value 
np.argmax(array1)

5

In [67]:
# find the min
np.min(array1)
# find the index of the minimum value 
np.argmin(array1)

0

In [69]:
# find the standard deviation
np.std(array1)

1.9790570145063195

In [70]:
# find the variance 
np.var(array1)

3.9166666666666665

Reshape and Transpose

In [71]:
array1.shape

(2, 3)

In [73]:
array1.reshape(2,3,1)

array([[[2],
        [3],
        [4]],

       [[4],
        [6],
        [8]]])

In [76]:
array_transpose = array1.transpose()

In [78]:
array_transpose.shape

(3, 2)

Dot product

In [79]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

In [80]:
np.dot(mat1, mat2)

array([[48, 66],
       [86, 66],
       [89, 39]])

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [85]:
# how to fix the above error 
np.dot(mat3, mat4.T)

array([[ 96,  48, 105,  60],
       [ 58,   8,  39,  39],
       [142,  32, 128,  86],
       [108,  72, 121,  73]])

Turning an image into a numpy array

In [2]:
from matplotlib.image import imread
chicken = imread('chicken_wings.jpeg')
print(type(chicken))

<class 'numpy.ndarray'>


In [3]:
chicken

array([[[140, 139, 145],
        [144, 143, 149],
        [153, 152, 158],
        ...,
        [243, 243, 243],
        [242, 242, 242],
        [240, 240, 240]],

       [[129, 128, 134],
        [135, 134, 140],
        [146, 145, 151],
        ...,
        [245, 245, 237],
        [243, 243, 235],
        [241, 241, 233]],

       [[138, 137, 143],
        [144, 143, 149],
        [152, 151, 157],
        ...,
        [251, 250, 229],
        [248, 247, 226],
        [245, 244, 223]],

       ...,

       [[142, 141, 149],
        [146, 145, 151],
        [143, 142, 148],
        ...,
        [ 44,  41,  34],
        [ 44,  41,  34],
        [ 43,  40,  33]],

       [[144, 143, 149],
        [141, 140, 146],
        [125, 124, 130],
        ...,
        [ 47,  48,  43],
        [ 38,  39,  34],
        [ 29,  30,  25]],

       [[152, 151, 157],
        [148, 147, 153],
        [130, 129, 135],
        ...,
        [ 46,  47,  42],
        [ 38,  39,  34],
        [ 29,  30,  25]]

In [5]:
chicken.shape # height, width, color channels

(194, 259, 3)